version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      frontend-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
